version: '3.8'
services:
  api-server:
    build: ./api-server
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - app-network


  s3-reverse-proxy:
    build: ./s3-reverse-proxy
    ports:
      - "8000:8000"
    environment:
       - NODE_ENV=production
       - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
